#----------------------------------------------------------------
# Generated CMake target import file for configuration "Debug".
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Compute the installation prefix relative to this file.
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Import target "vtksys" for configuration "Debug"
SET_PROPERTY(TARGET vtksys APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtksys PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ws2_32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtksys-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtksys )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtksys "${_IMPORT_PREFIX}/lib/vtk-5.8/vtksys-gd.lib" )

# Import target "vtkzlib" for configuration "Debug"
SET_PROPERTY(TARGET vtkzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkzlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkzlib-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkzlib )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkzlib "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkzlib-gd.lib" )

# Import target "vtkhdf5" for configuration "Debug"
SET_PROPERTY(TARGET vtkhdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkhdf5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ws2_32;wsock32;vtkzlib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkhdf5-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkhdf5 )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkhdf5 "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkhdf5-gd.lib" )

# Import target "vtkjpeg" for configuration "Debug"
SET_PROPERTY(TARGET vtkjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkjpeg-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkjpeg )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkjpeg "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkjpeg-gd.lib" )

# Import target "vtkpng" for configuration "Debug"
SET_PROPERTY(TARGET vtkpng APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkpng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkzlib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkpng-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkpng )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkpng "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkpng-gd.lib" )

# Import target "vtktiff" for configuration "Debug"
SET_PROPERTY(TARGET vtktiff APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtktiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkzlib;vtkjpeg"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtktiff-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtktiff )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtktiff "${_IMPORT_PREFIX}/lib/vtk-5.8/vtktiff-gd.lib" )

# Import target "vtkexpat" for configuration "Debug"
SET_PROPERTY(TARGET vtkexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkexpat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkexpat-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkexpat )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkexpat "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkexpat-gd.lib" )

# Import target "vtkfreetype" for configuration "Debug"
SET_PROPERTY(TARGET vtkfreetype APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkfreetype PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkfreetype-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkfreetype )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkfreetype "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkfreetype-gd.lib" )

# Import target "vtklibxml2" for configuration "Debug"
SET_PROPERTY(TARGET vtklibxml2 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtklibxml2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkzlib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtklibxml2-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtklibxml2 )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtklibxml2 "${_IMPORT_PREFIX}/lib/vtk-5.8/vtklibxml2-gd.lib" )

# Import target "vtkDICOMParser" for configuration "Debug"
SET_PROPERTY(TARGET vtkDICOMParser APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkDICOMParser PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkDICOMParser-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkDICOMParser )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkDICOMParser "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkDICOMParser-gd.lib" )

# Import target "vtkproj4" for configuration "Debug"
SET_PROPERTY(TARGET vtkproj4 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkproj4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkproj4-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkproj4 )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkproj4 "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkproj4-gd.lib" )

# Import target "mpistubs" for configuration "Debug"
SET_PROPERTY(TARGET mpistubs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(mpistubs PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtksys"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/mpistubs-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS mpistubs )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_mpistubs "${_IMPORT_PREFIX}/lib/vtk-5.8/mpistubs-gd.lib" )

# Import target "MapReduceMPI" for configuration "Debug"
SET_PROPERTY(TARGET MapReduceMPI APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(MapReduceMPI PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "mpistubs"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/MapReduceMPI-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS MapReduceMPI )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_MapReduceMPI "${_IMPORT_PREFIX}/lib/vtk-5.8/MapReduceMPI-gd.lib" )

# Import target "vtkverdict" for configuration "Debug"
SET_PROPERTY(TARGET vtkverdict APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkverdict PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkverdict-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkverdict )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkverdict "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkverdict-gd.lib" )

# Import target "vtkNetCDF" for configuration "Debug"
SET_PROPERTY(TARGET vtkNetCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkNetCDF PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkNetCDF-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkNetCDF )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkNetCDF "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkNetCDF-gd.lib" )

# Import target "vtkNetCDF_cxx" for configuration "Debug"
SET_PROPERTY(TARGET vtkNetCDF_cxx APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkNetCDF_cxx PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkNetCDF"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkNetCDF_cxx-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkNetCDF_cxx )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkNetCDF_cxx "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkNetCDF_cxx-gd.lib" )

# Import target "vtkmetaio" for configuration "Debug"
SET_PROPERTY(TARGET vtkmetaio APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkmetaio PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkzlib;vtksys;comctl32;wsock32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkmetaio-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkmetaio )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkmetaio "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkmetaio-gd.lib" )

# Import target "vtksqlite" for configuration "Debug"
SET_PROPERTY(TARGET vtksqlite APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtksqlite PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtksqlite-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtksqlite )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtksqlite "${_IMPORT_PREFIX}/lib/vtk-5.8/vtksqlite-gd.lib" )

# Import target "vtkexoIIc" for configuration "Debug"
SET_PROPERTY(TARGET vtkexoIIc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkexoIIc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkNetCDF"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkexoIIc-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkexoIIc )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkexoIIc "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkexoIIc-gd.lib" )

# Import target "vtkalglib" for configuration "Debug"
SET_PROPERTY(TARGET vtkalglib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkalglib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkalglib-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkalglib )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkalglib "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkalglib-gd.lib" )

# Import target "vtkEncodeString" for configuration "Debug"
SET_PROPERTY(TARGET vtkEncodeString APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkEncodeString PROPERTIES
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/bin/vtkEncodeString.exe"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkEncodeString )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkEncodeString "${_IMPORT_PREFIX}/bin/vtkEncodeString.exe" )

# Import target "vtkftgl" for configuration "Debug"
SET_PROPERTY(TARGET vtkftgl APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkftgl PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opengl32;vtkfreetype"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkftgl-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkftgl )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkftgl "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkftgl-gd.lib" )

# Import target "vtkCommon" for configuration "Debug"
SET_PROPERTY(TARGET vtkCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtksys;wsock32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkCommon-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkCommon )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkCommon "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkCommon-gd.lib" )

# Import target "vtkFiltering" for configuration "Debug"
SET_PROPERTY(TARGET vtkFiltering APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkFiltering PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkCommon"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkFiltering-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkFiltering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkFiltering "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkFiltering-gd.lib" )

# Import target "vtkImaging" for configuration "Debug"
SET_PROPERTY(TARGET vtkImaging APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkImaging PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkFiltering"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkImaging-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkImaging )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkImaging "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkImaging-gd.lib" )

# Import target "vtkGraphics" for configuration "Debug"
SET_PROPERTY(TARGET vtkGraphics APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkGraphics PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkFiltering;vtkverdict"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkGraphics-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkGraphics )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkGraphics "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkGraphics-gd.lib" )

# Import target "vtkGenericFiltering" for configuration "Debug"
SET_PROPERTY(TARGET vtkGenericFiltering APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkGenericFiltering PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkFiltering;vtkGraphics"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkGenericFiltering-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkGenericFiltering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkGenericFiltering "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkGenericFiltering-gd.lib" )

# Import target "vtkIO" for configuration "Debug"
SET_PROPERTY(TARGET vtkIO APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkIO PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkFiltering;vtkDICOMParser;vtkNetCDF;vtkNetCDF_cxx;vtkmetaio;vtksqlite;vtkpng;vtkzlib;vtkjpeg;vtktiff;vtkexpat;vtksys;vfw32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkIO-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkIO )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkIO "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkIO-gd.lib" )

# Import target "vtkRendering" for configuration "Debug"
SET_PROPERTY(TARGET vtkRendering APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkRendering PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkGraphics;vtkImaging;vtkIO;vtkftgl;vtkfreetype;C:/Qt/4.8.0/lib/QtGuid4.lib;C:/Qt/4.8.0/lib/QtSqld4.lib;C:/Qt/4.8.0/lib/QtCored4.lib;opengl32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkRendering-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkRendering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkRendering "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkRendering-gd.lib" )

# Import target "vtkVolumeRendering" for configuration "Debug"
SET_PROPERTY(TARGET vtkVolumeRendering APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkVolumeRendering PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkRendering;vtkIO;opengl32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkVolumeRendering-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkVolumeRendering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkVolumeRendering "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkVolumeRendering-gd.lib" )

# Import target "vtkHybrid" for configuration "Debug"
SET_PROPERTY(TARGET vtkHybrid APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkHybrid PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkRendering;vtkIO;vtkexoIIc;vfw32;vtkftgl"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkHybrid-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkHybrid )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkHybrid "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkHybrid-gd.lib" )

# Import target "vtkWidgets" for configuration "Debug"
SET_PROPERTY(TARGET vtkWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkWidgets PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkRendering;vtkHybrid;vtkVolumeRendering;opengl32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkWidgets-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkWidgets )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkWidgets "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkWidgets-gd.lib" )

# Import target "vtkInfovis" for configuration "Debug"
SET_PROPERTY(TARGET vtkInfovis APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkInfovis PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkWidgets;vtklibxml2;vtkalglib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkInfovis-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkInfovis )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkInfovis "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkInfovis-gd.lib" )

# Import target "vtkGeovis" for configuration "Debug"
SET_PROPERTY(TARGET vtkGeovis APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkGeovis PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkWidgets;vtkViews;vtkproj4"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkGeovis-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkGeovis )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkGeovis "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkGeovis-gd.lib" )

# Import target "vtkViews" for configuration "Debug"
SET_PROPERTY(TARGET vtkViews APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkViews PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkInfovis"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkViews-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkViews )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkViews "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkViews-gd.lib" )

# Import target "QVTK" for configuration "Debug"
SET_PROPERTY(TARGET QVTK APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(QVTK PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "C:/Qt/4.8.0/lib/QtOpenGLd4.lib;C:/Qt/4.8.0/lib/QtGuid4.lib;C:/Qt/4.8.0/lib/QtSqld4.lib;C:/Qt/4.8.0/lib/QtNetworkd4.lib;C:/Qt/4.8.0/lib/QtCored4.lib;vtkRendering;vtkGraphics;vtkImaging;vtkCommon;vtkViews;opengl32"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/QVTK-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS QVTK )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_QVTK "${_IMPORT_PREFIX}/lib/vtk-5.8/QVTK-gd.lib" )

# Import target "vtkCharts" for configuration "Debug"
SET_PROPERTY(TARGET vtkCharts APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
SET_TARGET_PROPERTIES(vtkCharts PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "vtkViews;vtkftgl;C:/Qt/4.8.0/lib/QtGuid4.lib;C:/Qt/4.8.0/lib/QtSqld4.lib;C:/Qt/4.8.0/lib/QtCored4.lib"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkCharts-gd.lib"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkCharts )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkCharts "${_IMPORT_PREFIX}/lib/vtk-5.8/vtkCharts-gd.lib" )

# Loop over all imported files and verify that they actually exist
FOREACH(target ${_IMPORT_CHECK_TARGETS} )
  FOREACH(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    IF(NOT EXISTS "${file}" )
      MESSAGE(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    ENDIF()
  ENDFOREACH()
  UNSET(_IMPORT_CHECK_FILES_FOR_${target})
ENDFOREACH()
UNSET(_IMPORT_CHECK_TARGETS)

# Cleanup temporary variables.
SET(_IMPORT_PREFIX)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
